package cn.nuist.aiarticlewriter.model.entity;

import com.mybatisflex.annotation.Column;
import com.mybatisflex.annotation.Id;
import com.mybatisflex.annotation.KeyType;
import com.mybatisflex.annotation.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Article entity.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(value = "article", camelToUnderline = false)
public class Article implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * Primary key, generated by database auto increment.
     */
    @Id(keyType = KeyType.Auto)
    private Long id;

    /**
     * Article generation task ID.
     */
    private String taskId;

    /**
     * User ID.
     */
    private Long userId;

    /**
     * Article topic.
     */
    private String topic;

    /**
     * Main title.
     */
    private String mainTitle;

    /**
     * Subtitle.
     */
    private String subTitle;

    /**
     * Candidate title options in JSON format.
     */
    private String titleOptions;

    /**
     * User writing requirement accumulated during creation.
     */
    private String userRequirement;

    /**
     * Current generation workflow step.
     */
    private String currentStep;

    /**
     * Article outline in JSON format.
     */
    private String outline;

    /**
     * Article content in Markdown format.
     */
    private String content;

    /**
     * Full article content with images in Markdown format.
     */
    private String fullContent;

    /**
     * Cover image URL.
     */
    private String coverImage;

    /**
     * Article image list in JSON format.
     */
    private String images;

    /**
     * Task status: PENDING/PROCESSING/WAITING_USER_INPUT/COMPLETED/FAILED.
     */
    private String status;

    /**
     * Error message.
     */
    private String errorMessage;

    /**
     * Create time.
     */
    private LocalDateTime createTime;

    /**
     * Task completion time.
     */
    private LocalDateTime completedTime;

    /**
     * Update time.
     */
    private LocalDateTime updateTime;

    /**
     * Logic delete flag.
     */
    @Column(isLogicDelete = true)
    private Integer isDelete;
}
