-- Database
CREATE DATABASE IF NOT EXISTS ai_article_writer
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE ai_article_writer;

-- User table
CREATE TABLE IF NOT EXISTS `user` (
    id BIGINT NOT NULL COMMENT 'Primary key, generated by Snowflake algorithm',
    userAccount VARCHAR(64) NOT NULL COMMENT 'User login account',
    userPassword VARCHAR(255) NOT NULL COMMENT 'Encrypted password',
    userName VARCHAR(64) DEFAULT NULL COMMENT 'User display name',
    userAvatar VARCHAR(512) DEFAULT NULL COMMENT 'User avatar URL',
    userProfile VARCHAR(512) DEFAULT NULL COMMENT 'User profile',
    userRole VARCHAR(32) NOT NULL DEFAULT 'user' COMMENT 'User role: user/admin',
    createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Business edit time',
    updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    isDelete TINYINT NOT NULL DEFAULT 0 COMMENT 'Logic delete flag: 0-normal, 1-deleted',
    PRIMARY KEY (id),
    UNIQUE KEY uk_userAccount (userAccount),
    KEY idx_userName (userName)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='User table';

-- Test data
INSERT INTO `user` (
    id,
    userAccount,
    userPassword,
    userName,
    userAvatar,
    userProfile,
    userRole
) VALUES
    (1000000000000000001, 'admin', 'admin_password_hash', 'admin', NULL, '系统管理员', 'admin'),
    (1000000000000000002, 'test_user', 'test_password_hash', '测试用户', NULL, '测试用户账号', 'user');
