-- Database
CREATE DATABASE IF NOT EXISTS ai_article_writer
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE ai_article_writer;

-- User table
CREATE TABLE IF NOT EXISTS `user` (
    id BIGINT NOT NULL COMMENT 'Primary key, generated by Snowflake algorithm',
    userAccount VARCHAR(64) NOT NULL COMMENT 'User login account',
    userPassword VARCHAR(255) NOT NULL COMMENT 'Encrypted password',
    userName VARCHAR(64) DEFAULT NULL COMMENT 'User display name',
    userAvatar VARCHAR(512) DEFAULT NULL COMMENT 'User avatar URL',
    userProfile VARCHAR(512) DEFAULT NULL COMMENT 'User profile',
    userRole VARCHAR(32) NOT NULL DEFAULT 'user' COMMENT 'User role: user/admin',
    vipTime DATETIME DEFAULT NULL COMMENT 'VIP activation time',
    createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    editTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Business edit time',
    updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    isDelete TINYINT NOT NULL DEFAULT 0 COMMENT 'Logic delete flag: 0-normal, 1-deleted',
    PRIMARY KEY (id),
    UNIQUE KEY uk_userAccount (userAccount),
    KEY idx_userName (userName)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='User table';

-- Article table
CREATE TABLE IF NOT EXISTS article (
    id BIGINT AUTO_INCREMENT COMMENT 'Primary key' PRIMARY KEY,
    taskId VARCHAR(64) NOT NULL COMMENT 'Article generation task ID',
    userId BIGINT NOT NULL COMMENT 'User ID',
    topic VARCHAR(500) NOT NULL COMMENT 'Article topic',
    mainTitle VARCHAR(200) DEFAULT NULL COMMENT 'Main title',
    subTitle VARCHAR(300) DEFAULT NULL COMMENT 'Subtitle',
    titleOptions JSON DEFAULT NULL COMMENT 'Candidate title options in JSON format',
    userRequirement TEXT DEFAULT NULL COMMENT 'User writing requirement accumulated during creation',
    currentStep VARCHAR(64) DEFAULT NULL COMMENT 'Current generation workflow step',
    outline JSON DEFAULT NULL COMMENT 'Article outline in JSON format',
    content MEDIUMTEXT DEFAULT NULL COMMENT 'Article content in Markdown format',
    fullContent MEDIUMTEXT DEFAULT NULL COMMENT 'Full article content with images in Markdown format',
    coverImage VARCHAR(512) DEFAULT NULL COMMENT 'Cover image URL',
    images JSON DEFAULT NULL COMMENT 'Article image list in JSON format',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'Task status: PENDING/PROCESSING/WAITING_USER_INPUT/COMPLETED/FAILED',
    errorMessage TEXT DEFAULT NULL COMMENT 'Error message',
    createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    completedTime DATETIME DEFAULT NULL COMMENT 'Task completion time',
    updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    isDelete TINYINT NOT NULL DEFAULT 0 COMMENT 'Logic delete flag: 0-normal, 1-deleted',
    UNIQUE KEY uk_taskId (taskId),
    KEY idx_userId (userId),
    KEY idx_status (status),
    KEY idx_createTime (createTime),
    KEY idx_userId_status (userId, status)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Article table';

-- Payment record table
CREATE TABLE IF NOT EXISTS payment_record (
    id BIGINT AUTO_INCREMENT COMMENT 'Primary key' PRIMARY KEY,
    userId BIGINT NOT NULL COMMENT 'User ID',
    stripeSessionId VARCHAR(128) DEFAULT NULL COMMENT 'Stripe Checkout Session ID',
    stripePaymentIntentId VARCHAR(128) DEFAULT NULL COMMENT 'Stripe PaymentIntent ID',
    amount DECIMAL(10, 2) NOT NULL COMMENT 'Amount in major currency unit',
    currency VARCHAR(8) NOT NULL DEFAULT 'usd' COMMENT 'Currency',
    status VARCHAR(32) NOT NULL COMMENT 'Status: PENDING/SUCCEEDED/FAILED/REFUNDED',
    productType VARCHAR(32) NOT NULL COMMENT 'Product type: VIP_PERMANENT',
    description VARCHAR(256) DEFAULT NULL COMMENT 'Description',
    refundTime DATETIME DEFAULT NULL COMMENT 'Refund time',
    refundReason VARCHAR(512) DEFAULT NULL COMMENT 'Refund reason',
    createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    KEY idx_userId (userId),
    KEY idx_stripeSessionId (stripeSessionId),
    KEY idx_status (status),
    KEY idx_createTime (createTime)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Payment record table';

-- Agent execution log table
CREATE TABLE IF NOT EXISTS agent_log (
    id BIGINT AUTO_INCREMENT COMMENT 'Primary key' PRIMARY KEY,
    taskId VARCHAR(64) NOT NULL COMMENT 'Article generation task ID',
    agentName VARCHAR(50) NOT NULL COMMENT 'Agent name',
    startTime DATETIME NOT NULL COMMENT 'Start time',
    endTime DATETIME DEFAULT NULL COMMENT 'End time',
    durationMs INT DEFAULT NULL COMMENT 'Duration in milliseconds',
    status VARCHAR(20) NOT NULL COMMENT 'Status: SUCCESS/FAILED',
    errorMessage TEXT DEFAULT NULL COMMENT 'Error message',
    prompt TEXT DEFAULT NULL COMMENT 'Prompt identifier or prompt summary',
    inputData JSON DEFAULT NULL COMMENT 'Input data in JSON format',
    outputData JSON DEFAULT NULL COMMENT 'Output data in JSON format',
    createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    updateTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    isDelete TINYINT NOT NULL DEFAULT 0 COMMENT 'Logic delete flag: 0-normal, 1-deleted',
    KEY idx_taskId (taskId),
    KEY idx_agentName (agentName),
    KEY idx_status (status),
    KEY idx_createTime (createTime)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Agent execution log table';

-- Test data
-- Default credentials:
-- admin / admin1234
-- test_user / test1234
INSERT INTO `user` (
    id,
    userAccount,
    userPassword,
    userName,
    userAvatar,
    userProfile,
    userRole
) VALUES
    (1000000000000000001, 'admin', '98dec0af5c1db56bc34188e01c9e2ced', 'admin', NULL, 'System administrator', 'admin'),
    (1000000000000000002, 'test_user', '103443bedcb2140e97854980db798ce4', 'test_user', NULL, 'Test user account', 'user');
